export const CHANGE_SPECIALIZATION = 'app/FormSearchInput/SpecializationSelect/CHANGE_SPECIALIZATION'
export const LOAD_SPECIALIZATIONS = 'app/FormSearchInput/SpecializationSelect/LOADING_SPECIALIZATIONS'
export const LOAD_SPECIALIZATIONS_SUCCESS = 'app/FormSearchInput/SpecializationSelect/LOAD_SPECIALIZATIONS_SUCCESS'
export const LOAD_SPECIALIZATIONS_ERROR = 'app/FormSearchInput/SpecializationSelect/LOAD_SPECIALIZATIONS_ERROR'
export const RESET_SPECIALIZATION_VALUE = 'app/FormSearchInput/SpecializationSelect/RESET_SPECIALIZATION_VALUE'
