export const LOAD_ANALYSIS = 'app/PieChart/LOAD_ANALYSIS'
export const LOAD_ANALYSIS_SUCCESS = 'app/PieChart/LOAD_ANALYSIS_SUCCESS'
export const LOAD_ANALYSIS_ERROR = 'app/PieChart/LOAD_ANALYSIS_ERROR'
